/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.finaxys.tutorials.utils.avro.models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Day extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Day\",\"namespace\":\"fr.finaxys.tutorials.utils.avro.models\",\"fields\":[{\"name\":\"Trace\",\"type\":\"string\"},{\"name\":\"NumDay\",\"type\":\"int\"},{\"name\":\"ObName\",\"type\":\"string\"},{\"name\":\"FirstFixedPrice\",\"type\":\"long\"},{\"name\":\"LowestPrice\",\"type\":\"long\"},{\"name\":\"HighestPrice\",\"type\":\"long\"},{\"name\":\"LastFixedPrice\",\"type\":\"long\"},{\"name\":\"NbPricesFixed\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence Trace;
  @Deprecated public int NumDay;
  @Deprecated public java.lang.CharSequence ObName;
  @Deprecated public long FirstFixedPrice;
  @Deprecated public long LowestPrice;
  @Deprecated public long HighestPrice;
  @Deprecated public long LastFixedPrice;
  @Deprecated public long NbPricesFixed;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Day() {}

  /**
   * All-args constructor.
   */
  public Day(java.lang.CharSequence Trace, java.lang.Integer NumDay, java.lang.CharSequence ObName, java.lang.Long FirstFixedPrice, java.lang.Long LowestPrice, java.lang.Long HighestPrice, java.lang.Long LastFixedPrice, java.lang.Long NbPricesFixed) {
    this.Trace = Trace;
    this.NumDay = NumDay;
    this.ObName = ObName;
    this.FirstFixedPrice = FirstFixedPrice;
    this.LowestPrice = LowestPrice;
    this.HighestPrice = HighestPrice;
    this.LastFixedPrice = LastFixedPrice;
    this.NbPricesFixed = NbPricesFixed;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Trace;
    case 1: return NumDay;
    case 2: return ObName;
    case 3: return FirstFixedPrice;
    case 4: return LowestPrice;
    case 5: return HighestPrice;
    case 6: return LastFixedPrice;
    case 7: return NbPricesFixed;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Trace = (java.lang.CharSequence)value$; break;
    case 1: NumDay = (java.lang.Integer)value$; break;
    case 2: ObName = (java.lang.CharSequence)value$; break;
    case 3: FirstFixedPrice = (java.lang.Long)value$; break;
    case 4: LowestPrice = (java.lang.Long)value$; break;
    case 5: HighestPrice = (java.lang.Long)value$; break;
    case 6: LastFixedPrice = (java.lang.Long)value$; break;
    case 7: NbPricesFixed = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Trace' field.
   */
  public java.lang.CharSequence getTrace() {
    return Trace;
  }

  /**
   * Sets the value of the 'Trace' field.
   * @param value the value to set.
   */
  public void setTrace(java.lang.CharSequence value) {
    this.Trace = value;
  }

  /**
   * Gets the value of the 'NumDay' field.
   */
  public java.lang.Integer getNumDay() {
    return NumDay;
  }

  /**
   * Sets the value of the 'NumDay' field.
   * @param value the value to set.
   */
  public void setNumDay(java.lang.Integer value) {
    this.NumDay = value;
  }

  /**
   * Gets the value of the 'ObName' field.
   */
  public java.lang.CharSequence getObName() {
    return ObName;
  }

  /**
   * Sets the value of the 'ObName' field.
   * @param value the value to set.
   */
  public void setObName(java.lang.CharSequence value) {
    this.ObName = value;
  }

  /**
   * Gets the value of the 'FirstFixedPrice' field.
   */
  public java.lang.Long getFirstFixedPrice() {
    return FirstFixedPrice;
  }

  /**
   * Sets the value of the 'FirstFixedPrice' field.
   * @param value the value to set.
   */
  public void setFirstFixedPrice(java.lang.Long value) {
    this.FirstFixedPrice = value;
  }

  /**
   * Gets the value of the 'LowestPrice' field.
   */
  public java.lang.Long getLowestPrice() {
    return LowestPrice;
  }

  /**
   * Sets the value of the 'LowestPrice' field.
   * @param value the value to set.
   */
  public void setLowestPrice(java.lang.Long value) {
    this.LowestPrice = value;
  }

  /**
   * Gets the value of the 'HighestPrice' field.
   */
  public java.lang.Long getHighestPrice() {
    return HighestPrice;
  }

  /**
   * Sets the value of the 'HighestPrice' field.
   * @param value the value to set.
   */
  public void setHighestPrice(java.lang.Long value) {
    this.HighestPrice = value;
  }

  /**
   * Gets the value of the 'LastFixedPrice' field.
   */
  public java.lang.Long getLastFixedPrice() {
    return LastFixedPrice;
  }

  /**
   * Sets the value of the 'LastFixedPrice' field.
   * @param value the value to set.
   */
  public void setLastFixedPrice(java.lang.Long value) {
    this.LastFixedPrice = value;
  }

  /**
   * Gets the value of the 'NbPricesFixed' field.
   */
  public java.lang.Long getNbPricesFixed() {
    return NbPricesFixed;
  }

  /**
   * Sets the value of the 'NbPricesFixed' field.
   * @param value the value to set.
   */
  public void setNbPricesFixed(java.lang.Long value) {
    this.NbPricesFixed = value;
  }

  /** Creates a new Day RecordBuilder */
  public static fr.finaxys.tutorials.utils.avro.models.Day.Builder newBuilder() {
    return new fr.finaxys.tutorials.utils.avro.models.Day.Builder();
  }
  
  /** Creates a new Day RecordBuilder by copying an existing Builder */
  public static fr.finaxys.tutorials.utils.avro.models.Day.Builder newBuilder(fr.finaxys.tutorials.utils.avro.models.Day.Builder other) {
    return new fr.finaxys.tutorials.utils.avro.models.Day.Builder(other);
  }
  
  /** Creates a new Day RecordBuilder by copying an existing Day instance */
  public static fr.finaxys.tutorials.utils.avro.models.Day.Builder newBuilder(fr.finaxys.tutorials.utils.avro.models.Day other) {
    return new fr.finaxys.tutorials.utils.avro.models.Day.Builder(other);
  }
  
  /**
   * RecordBuilder for Day instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Day>
    implements org.apache.avro.data.RecordBuilder<Day> {

    private java.lang.CharSequence Trace;
    private int NumDay;
    private java.lang.CharSequence ObName;
    private long FirstFixedPrice;
    private long LowestPrice;
    private long HighestPrice;
    private long LastFixedPrice;
    private long NbPricesFixed;

    /** Creates a new Builder */
    private Builder() {
      super(fr.finaxys.tutorials.utils.avro.models.Day.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.finaxys.tutorials.utils.avro.models.Day.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Trace)) {
        this.Trace = data().deepCopy(fields()[0].schema(), other.Trace);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.NumDay)) {
        this.NumDay = data().deepCopy(fields()[1].schema(), other.NumDay);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ObName)) {
        this.ObName = data().deepCopy(fields()[2].schema(), other.ObName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.FirstFixedPrice)) {
        this.FirstFixedPrice = data().deepCopy(fields()[3].schema(), other.FirstFixedPrice);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.LowestPrice)) {
        this.LowestPrice = data().deepCopy(fields()[4].schema(), other.LowestPrice);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.HighestPrice)) {
        this.HighestPrice = data().deepCopy(fields()[5].schema(), other.HighestPrice);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.LastFixedPrice)) {
        this.LastFixedPrice = data().deepCopy(fields()[6].schema(), other.LastFixedPrice);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.NbPricesFixed)) {
        this.NbPricesFixed = data().deepCopy(fields()[7].schema(), other.NbPricesFixed);
        fieldSetFlags()[7] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Day instance */
    private Builder(fr.finaxys.tutorials.utils.avro.models.Day other) {
            super(fr.finaxys.tutorials.utils.avro.models.Day.SCHEMA$);
      if (isValidValue(fields()[0], other.Trace)) {
        this.Trace = data().deepCopy(fields()[0].schema(), other.Trace);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.NumDay)) {
        this.NumDay = data().deepCopy(fields()[1].schema(), other.NumDay);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ObName)) {
        this.ObName = data().deepCopy(fields()[2].schema(), other.ObName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.FirstFixedPrice)) {
        this.FirstFixedPrice = data().deepCopy(fields()[3].schema(), other.FirstFixedPrice);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.LowestPrice)) {
        this.LowestPrice = data().deepCopy(fields()[4].schema(), other.LowestPrice);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.HighestPrice)) {
        this.HighestPrice = data().deepCopy(fields()[5].schema(), other.HighestPrice);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.LastFixedPrice)) {
        this.LastFixedPrice = data().deepCopy(fields()[6].schema(), other.LastFixedPrice);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.NbPricesFixed)) {
        this.NbPricesFixed = data().deepCopy(fields()[7].schema(), other.NbPricesFixed);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'Trace' field */
    public java.lang.CharSequence getTrace() {
      return Trace;
    }
    
    /** Sets the value of the 'Trace' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder setTrace(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Trace = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'Trace' field has been set */
    public boolean hasTrace() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'Trace' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder clearTrace() {
      Trace = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'NumDay' field */
    public java.lang.Integer getNumDay() {
      return NumDay;
    }
    
    /** Sets the value of the 'NumDay' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder setNumDay(int value) {
      validate(fields()[1], value);
      this.NumDay = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'NumDay' field has been set */
    public boolean hasNumDay() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'NumDay' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder clearNumDay() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'ObName' field */
    public java.lang.CharSequence getObName() {
      return ObName;
    }
    
    /** Sets the value of the 'ObName' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder setObName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ObName = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'ObName' field has been set */
    public boolean hasObName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'ObName' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder clearObName() {
      ObName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'FirstFixedPrice' field */
    public java.lang.Long getFirstFixedPrice() {
      return FirstFixedPrice;
    }
    
    /** Sets the value of the 'FirstFixedPrice' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder setFirstFixedPrice(long value) {
      validate(fields()[3], value);
      this.FirstFixedPrice = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'FirstFixedPrice' field has been set */
    public boolean hasFirstFixedPrice() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'FirstFixedPrice' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder clearFirstFixedPrice() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'LowestPrice' field */
    public java.lang.Long getLowestPrice() {
      return LowestPrice;
    }
    
    /** Sets the value of the 'LowestPrice' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder setLowestPrice(long value) {
      validate(fields()[4], value);
      this.LowestPrice = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'LowestPrice' field has been set */
    public boolean hasLowestPrice() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'LowestPrice' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder clearLowestPrice() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'HighestPrice' field */
    public java.lang.Long getHighestPrice() {
      return HighestPrice;
    }
    
    /** Sets the value of the 'HighestPrice' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder setHighestPrice(long value) {
      validate(fields()[5], value);
      this.HighestPrice = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'HighestPrice' field has been set */
    public boolean hasHighestPrice() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'HighestPrice' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder clearHighestPrice() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'LastFixedPrice' field */
    public java.lang.Long getLastFixedPrice() {
      return LastFixedPrice;
    }
    
    /** Sets the value of the 'LastFixedPrice' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder setLastFixedPrice(long value) {
      validate(fields()[6], value);
      this.LastFixedPrice = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'LastFixedPrice' field has been set */
    public boolean hasLastFixedPrice() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'LastFixedPrice' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder clearLastFixedPrice() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'NbPricesFixed' field */
    public java.lang.Long getNbPricesFixed() {
      return NbPricesFixed;
    }
    
    /** Sets the value of the 'NbPricesFixed' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder setNbPricesFixed(long value) {
      validate(fields()[7], value);
      this.NbPricesFixed = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'NbPricesFixed' field has been set */
    public boolean hasNbPricesFixed() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'NbPricesFixed' field */
    public fr.finaxys.tutorials.utils.avro.models.Day.Builder clearNbPricesFixed() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public Day build() {
      try {
        Day record = new Day();
        record.Trace = fieldSetFlags()[0] ? this.Trace : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.NumDay = fieldSetFlags()[1] ? this.NumDay : (java.lang.Integer) defaultValue(fields()[1]);
        record.ObName = fieldSetFlags()[2] ? this.ObName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.FirstFixedPrice = fieldSetFlags()[3] ? this.FirstFixedPrice : (java.lang.Long) defaultValue(fields()[3]);
        record.LowestPrice = fieldSetFlags()[4] ? this.LowestPrice : (java.lang.Long) defaultValue(fields()[4]);
        record.HighestPrice = fieldSetFlags()[5] ? this.HighestPrice : (java.lang.Long) defaultValue(fields()[5]);
        record.LastFixedPrice = fieldSetFlags()[6] ? this.LastFixedPrice : (java.lang.Long) defaultValue(fields()[6]);
        record.NbPricesFixed = fieldSetFlags()[7] ? this.NbPricesFixed : (java.lang.Long) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
