/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.finaxys.tutorials.utils.avro.models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Order extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"fr.finaxys.tutorials.utils.avro.models\",\"fields\":[{\"name\":\"Trace\",\"type\":\"string\"},{\"name\":\"ObName\",\"type\":\"string\"},{\"name\":\"Sender\",\"type\":\"string\"},{\"name\":\"ExtId\",\"type\":\"string\"},{\"name\":\"Type\",\"type\":\"string\"},{\"name\":\"Id\",\"type\":\"long\"},{\"name\":\"Quantity\",\"type\":\"int\"},{\"name\":\"Direction\",\"type\":\"string\"},{\"name\":\"Price\",\"type\":\"long\"},{\"name\":\"Validity\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence Trace;
  @Deprecated public java.lang.CharSequence ObName;
  @Deprecated public java.lang.CharSequence Sender;
  @Deprecated public java.lang.CharSequence ExtId;
  @Deprecated public java.lang.CharSequence Type;
  @Deprecated public long Id;
  @Deprecated public int Quantity;
  @Deprecated public java.lang.CharSequence Direction;
  @Deprecated public long Price;
  @Deprecated public long Validity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Order() {}

  /**
   * All-args constructor.
   */
  public Order(java.lang.CharSequence Trace, java.lang.CharSequence ObName, java.lang.CharSequence Sender, java.lang.CharSequence ExtId, java.lang.CharSequence Type, java.lang.Long Id, java.lang.Integer Quantity, java.lang.CharSequence Direction, java.lang.Long Price, java.lang.Long Validity) {
    this.Trace = Trace;
    this.ObName = ObName;
    this.Sender = Sender;
    this.ExtId = ExtId;
    this.Type = Type;
    this.Id = Id;
    this.Quantity = Quantity;
    this.Direction = Direction;
    this.Price = Price;
    this.Validity = Validity;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Trace;
    case 1: return ObName;
    case 2: return Sender;
    case 3: return ExtId;
    case 4: return Type;
    case 5: return Id;
    case 6: return Quantity;
    case 7: return Direction;
    case 8: return Price;
    case 9: return Validity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Trace = (java.lang.CharSequence)value$; break;
    case 1: ObName = (java.lang.CharSequence)value$; break;
    case 2: Sender = (java.lang.CharSequence)value$; break;
    case 3: ExtId = (java.lang.CharSequence)value$; break;
    case 4: Type = (java.lang.CharSequence)value$; break;
    case 5: Id = (java.lang.Long)value$; break;
    case 6: Quantity = (java.lang.Integer)value$; break;
    case 7: Direction = (java.lang.CharSequence)value$; break;
    case 8: Price = (java.lang.Long)value$; break;
    case 9: Validity = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Trace' field.
   */
  public java.lang.CharSequence getTrace() {
    return Trace;
  }

  /**
   * Sets the value of the 'Trace' field.
   * @param value the value to set.
   */
  public void setTrace(java.lang.CharSequence value) {
    this.Trace = value;
  }

  /**
   * Gets the value of the 'ObName' field.
   */
  public java.lang.CharSequence getObName() {
    return ObName;
  }

  /**
   * Sets the value of the 'ObName' field.
   * @param value the value to set.
   */
  public void setObName(java.lang.CharSequence value) {
    this.ObName = value;
  }

  /**
   * Gets the value of the 'Sender' field.
   */
  public java.lang.CharSequence getSender() {
    return Sender;
  }

  /**
   * Sets the value of the 'Sender' field.
   * @param value the value to set.
   */
  public void setSender(java.lang.CharSequence value) {
    this.Sender = value;
  }

  /**
   * Gets the value of the 'ExtId' field.
   */
  public java.lang.CharSequence getExtId() {
    return ExtId;
  }

  /**
   * Sets the value of the 'ExtId' field.
   * @param value the value to set.
   */
  public void setExtId(java.lang.CharSequence value) {
    this.ExtId = value;
  }

  /**
   * Gets the value of the 'Type' field.
   */
  public java.lang.CharSequence getType() {
    return Type;
  }

  /**
   * Sets the value of the 'Type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.Type = value;
  }

  /**
   * Gets the value of the 'Id' field.
   */
  public java.lang.Long getId() {
    return Id;
  }

  /**
   * Sets the value of the 'Id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.Id = value;
  }

  /**
   * Gets the value of the 'Quantity' field.
   */
  public java.lang.Integer getQuantity() {
    return Quantity;
  }

  /**
   * Sets the value of the 'Quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.lang.Integer value) {
    this.Quantity = value;
  }

  /**
   * Gets the value of the 'Direction' field.
   */
  public java.lang.CharSequence getDirection() {
    return Direction;
  }

  /**
   * Sets the value of the 'Direction' field.
   * @param value the value to set.
   */
  public void setDirection(java.lang.CharSequence value) {
    this.Direction = value;
  }

  /**
   * Gets the value of the 'Price' field.
   */
  public java.lang.Long getPrice() {
    return Price;
  }

  /**
   * Sets the value of the 'Price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Long value) {
    this.Price = value;
  }

  /**
   * Gets the value of the 'Validity' field.
   */
  public java.lang.Long getValidity() {
    return Validity;
  }

  /**
   * Sets the value of the 'Validity' field.
   * @param value the value to set.
   */
  public void setValidity(java.lang.Long value) {
    this.Validity = value;
  }

  /** Creates a new Order RecordBuilder */
  public static fr.finaxys.tutorials.utils.avro.models.Order.Builder newBuilder() {
    return new fr.finaxys.tutorials.utils.avro.models.Order.Builder();
  }
  
  /** Creates a new Order RecordBuilder by copying an existing Builder */
  public static fr.finaxys.tutorials.utils.avro.models.Order.Builder newBuilder(fr.finaxys.tutorials.utils.avro.models.Order.Builder other) {
    return new fr.finaxys.tutorials.utils.avro.models.Order.Builder(other);
  }
  
  /** Creates a new Order RecordBuilder by copying an existing Order instance */
  public static fr.finaxys.tutorials.utils.avro.models.Order.Builder newBuilder(fr.finaxys.tutorials.utils.avro.models.Order other) {
    return new fr.finaxys.tutorials.utils.avro.models.Order.Builder(other);
  }
  
  /**
   * RecordBuilder for Order instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Order>
    implements org.apache.avro.data.RecordBuilder<Order> {

    private java.lang.CharSequence Trace;
    private java.lang.CharSequence ObName;
    private java.lang.CharSequence Sender;
    private java.lang.CharSequence ExtId;
    private java.lang.CharSequence Type;
    private long Id;
    private int Quantity;
    private java.lang.CharSequence Direction;
    private long Price;
    private long Validity;

    /** Creates a new Builder */
    private Builder() {
      super(fr.finaxys.tutorials.utils.avro.models.Order.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.finaxys.tutorials.utils.avro.models.Order.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Trace)) {
        this.Trace = data().deepCopy(fields()[0].schema(), other.Trace);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ObName)) {
        this.ObName = data().deepCopy(fields()[1].schema(), other.ObName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Sender)) {
        this.Sender = data().deepCopy(fields()[2].schema(), other.Sender);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ExtId)) {
        this.ExtId = data().deepCopy(fields()[3].schema(), other.ExtId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Type)) {
        this.Type = data().deepCopy(fields()[4].schema(), other.Type);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.Id)) {
        this.Id = data().deepCopy(fields()[5].schema(), other.Id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.Quantity)) {
        this.Quantity = data().deepCopy(fields()[6].schema(), other.Quantity);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.Direction)) {
        this.Direction = data().deepCopy(fields()[7].schema(), other.Direction);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.Price)) {
        this.Price = data().deepCopy(fields()[8].schema(), other.Price);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.Validity)) {
        this.Validity = data().deepCopy(fields()[9].schema(), other.Validity);
        fieldSetFlags()[9] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Order instance */
    private Builder(fr.finaxys.tutorials.utils.avro.models.Order other) {
            super(fr.finaxys.tutorials.utils.avro.models.Order.SCHEMA$);
      if (isValidValue(fields()[0], other.Trace)) {
        this.Trace = data().deepCopy(fields()[0].schema(), other.Trace);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ObName)) {
        this.ObName = data().deepCopy(fields()[1].schema(), other.ObName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Sender)) {
        this.Sender = data().deepCopy(fields()[2].schema(), other.Sender);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ExtId)) {
        this.ExtId = data().deepCopy(fields()[3].schema(), other.ExtId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Type)) {
        this.Type = data().deepCopy(fields()[4].schema(), other.Type);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.Id)) {
        this.Id = data().deepCopy(fields()[5].schema(), other.Id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.Quantity)) {
        this.Quantity = data().deepCopy(fields()[6].schema(), other.Quantity);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.Direction)) {
        this.Direction = data().deepCopy(fields()[7].schema(), other.Direction);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.Price)) {
        this.Price = data().deepCopy(fields()[8].schema(), other.Price);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.Validity)) {
        this.Validity = data().deepCopy(fields()[9].schema(), other.Validity);
        fieldSetFlags()[9] = true;
      }
    }

    /** Gets the value of the 'Trace' field */
    public java.lang.CharSequence getTrace() {
      return Trace;
    }
    
    /** Sets the value of the 'Trace' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder setTrace(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Trace = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'Trace' field has been set */
    public boolean hasTrace() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'Trace' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder clearTrace() {
      Trace = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'ObName' field */
    public java.lang.CharSequence getObName() {
      return ObName;
    }
    
    /** Sets the value of the 'ObName' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder setObName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.ObName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'ObName' field has been set */
    public boolean hasObName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'ObName' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder clearObName() {
      ObName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'Sender' field */
    public java.lang.CharSequence getSender() {
      return Sender;
    }
    
    /** Sets the value of the 'Sender' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder setSender(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.Sender = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'Sender' field has been set */
    public boolean hasSender() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'Sender' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder clearSender() {
      Sender = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ExtId' field */
    public java.lang.CharSequence getExtId() {
      return ExtId;
    }
    
    /** Sets the value of the 'ExtId' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder setExtId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ExtId = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ExtId' field has been set */
    public boolean hasExtId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ExtId' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder clearExtId() {
      ExtId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'Type' field */
    public java.lang.CharSequence getType() {
      return Type;
    }
    
    /** Sets the value of the 'Type' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder setType(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.Type = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'Type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'Type' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder clearType() {
      Type = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'Id' field */
    public java.lang.Long getId() {
      return Id;
    }
    
    /** Sets the value of the 'Id' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder setId(long value) {
      validate(fields()[5], value);
      this.Id = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'Id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'Id' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder clearId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'Quantity' field */
    public java.lang.Integer getQuantity() {
      return Quantity;
    }
    
    /** Sets the value of the 'Quantity' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder setQuantity(int value) {
      validate(fields()[6], value);
      this.Quantity = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'Quantity' field has been set */
    public boolean hasQuantity() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'Quantity' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder clearQuantity() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'Direction' field */
    public java.lang.CharSequence getDirection() {
      return Direction;
    }
    
    /** Sets the value of the 'Direction' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder setDirection(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.Direction = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'Direction' field has been set */
    public boolean hasDirection() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'Direction' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder clearDirection() {
      Direction = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'Price' field */
    public java.lang.Long getPrice() {
      return Price;
    }
    
    /** Sets the value of the 'Price' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder setPrice(long value) {
      validate(fields()[8], value);
      this.Price = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'Price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'Price' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder clearPrice() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'Validity' field */
    public java.lang.Long getValidity() {
      return Validity;
    }
    
    /** Sets the value of the 'Validity' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder setValidity(long value) {
      validate(fields()[9], value);
      this.Validity = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'Validity' field has been set */
    public boolean hasValidity() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'Validity' field */
    public fr.finaxys.tutorials.utils.avro.models.Order.Builder clearValidity() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    public Order build() {
      try {
        Order record = new Order();
        record.Trace = fieldSetFlags()[0] ? this.Trace : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.ObName = fieldSetFlags()[1] ? this.ObName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Sender = fieldSetFlags()[2] ? this.Sender : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ExtId = fieldSetFlags()[3] ? this.ExtId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.Type = fieldSetFlags()[4] ? this.Type : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.Id = fieldSetFlags()[5] ? this.Id : (java.lang.Long) defaultValue(fields()[5]);
        record.Quantity = fieldSetFlags()[6] ? this.Quantity : (java.lang.Integer) defaultValue(fields()[6]);
        record.Direction = fieldSetFlags()[7] ? this.Direction : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.Price = fieldSetFlags()[8] ? this.Price : (java.lang.Long) defaultValue(fields()[8]);
        record.Validity = fieldSetFlags()[9] ? this.Validity : (java.lang.Long) defaultValue(fields()[9]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
