/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package fr.finaxys.tutorials.utils.avro.models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Tick extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Tick\",\"namespace\":\"fr.finaxys.tutorials.utils.avro.models\",\"fields\":[{\"name\":\"Trace\",\"type\":\"string\"},{\"name\":\"NumTick\",\"type\":\"int\"},{\"name\":\"NumDay\",\"type\":\"int\"},{\"name\":\"ObName\",\"type\":\"string\"},{\"name\":\"Timestamp\",\"type\":\"long\"},{\"name\":\"BestAsk\",\"type\":\"long\"},{\"name\":\"BestBid\",\"type\":\"long\"},{\"name\":\"LastFixedPrice\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence Trace;
  @Deprecated public int NumTick;
  @Deprecated public int NumDay;
  @Deprecated public java.lang.CharSequence ObName;
  @Deprecated public long Timestamp;
  @Deprecated public long BestAsk;
  @Deprecated public long BestBid;
  @Deprecated public long LastFixedPrice;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Tick() {}

  /**
   * All-args constructor.
   */
  public Tick(java.lang.CharSequence Trace, java.lang.Integer NumTick, java.lang.Integer NumDay, java.lang.CharSequence ObName, java.lang.Long Timestamp, java.lang.Long BestAsk, java.lang.Long BestBid, java.lang.Long LastFixedPrice) {
    this.Trace = Trace;
    this.NumTick = NumTick;
    this.NumDay = NumDay;
    this.ObName = ObName;
    this.Timestamp = Timestamp;
    this.BestAsk = BestAsk;
    this.BestBid = BestBid;
    this.LastFixedPrice = LastFixedPrice;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Trace;
    case 1: return NumTick;
    case 2: return NumDay;
    case 3: return ObName;
    case 4: return Timestamp;
    case 5: return BestAsk;
    case 6: return BestBid;
    case 7: return LastFixedPrice;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Trace = (java.lang.CharSequence)value$; break;
    case 1: NumTick = (java.lang.Integer)value$; break;
    case 2: NumDay = (java.lang.Integer)value$; break;
    case 3: ObName = (java.lang.CharSequence)value$; break;
    case 4: Timestamp = (java.lang.Long)value$; break;
    case 5: BestAsk = (java.lang.Long)value$; break;
    case 6: BestBid = (java.lang.Long)value$; break;
    case 7: LastFixedPrice = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Trace' field.
   */
  public java.lang.CharSequence getTrace() {
    return Trace;
  }

  /**
   * Sets the value of the 'Trace' field.
   * @param value the value to set.
   */
  public void setTrace(java.lang.CharSequence value) {
    this.Trace = value;
  }

  /**
   * Gets the value of the 'NumTick' field.
   */
  public java.lang.Integer getNumTick() {
    return NumTick;
  }

  /**
   * Sets the value of the 'NumTick' field.
   * @param value the value to set.
   */
  public void setNumTick(java.lang.Integer value) {
    this.NumTick = value;
  }

  /**
   * Gets the value of the 'NumDay' field.
   */
  public java.lang.Integer getNumDay() {
    return NumDay;
  }

  /**
   * Sets the value of the 'NumDay' field.
   * @param value the value to set.
   */
  public void setNumDay(java.lang.Integer value) {
    this.NumDay = value;
  }

  /**
   * Gets the value of the 'ObName' field.
   */
  public java.lang.CharSequence getObName() {
    return ObName;
  }

  /**
   * Sets the value of the 'ObName' field.
   * @param value the value to set.
   */
  public void setObName(java.lang.CharSequence value) {
    this.ObName = value;
  }

  /**
   * Gets the value of the 'Timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return Timestamp;
  }

  /**
   * Sets the value of the 'Timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.Timestamp = value;
  }

  /**
   * Gets the value of the 'BestAsk' field.
   */
  public java.lang.Long getBestAsk() {
    return BestAsk;
  }

  /**
   * Sets the value of the 'BestAsk' field.
   * @param value the value to set.
   */
  public void setBestAsk(java.lang.Long value) {
    this.BestAsk = value;
  }

  /**
   * Gets the value of the 'BestBid' field.
   */
  public java.lang.Long getBestBid() {
    return BestBid;
  }

  /**
   * Sets the value of the 'BestBid' field.
   * @param value the value to set.
   */
  public void setBestBid(java.lang.Long value) {
    this.BestBid = value;
  }

  /**
   * Gets the value of the 'LastFixedPrice' field.
   */
  public java.lang.Long getLastFixedPrice() {
    return LastFixedPrice;
  }

  /**
   * Sets the value of the 'LastFixedPrice' field.
   * @param value the value to set.
   */
  public void setLastFixedPrice(java.lang.Long value) {
    this.LastFixedPrice = value;
  }

  /** Creates a new Tick RecordBuilder */
  public static fr.finaxys.tutorials.utils.avro.models.Tick.Builder newBuilder() {
    return new fr.finaxys.tutorials.utils.avro.models.Tick.Builder();
  }
  
  /** Creates a new Tick RecordBuilder by copying an existing Builder */
  public static fr.finaxys.tutorials.utils.avro.models.Tick.Builder newBuilder(fr.finaxys.tutorials.utils.avro.models.Tick.Builder other) {
    return new fr.finaxys.tutorials.utils.avro.models.Tick.Builder(other);
  }
  
  /** Creates a new Tick RecordBuilder by copying an existing Tick instance */
  public static fr.finaxys.tutorials.utils.avro.models.Tick.Builder newBuilder(fr.finaxys.tutorials.utils.avro.models.Tick other) {
    return new fr.finaxys.tutorials.utils.avro.models.Tick.Builder(other);
  }
  
  /**
   * RecordBuilder for Tick instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Tick>
    implements org.apache.avro.data.RecordBuilder<Tick> {

    private java.lang.CharSequence Trace;
    private int NumTick;
    private int NumDay;
    private java.lang.CharSequence ObName;
    private long Timestamp;
    private long BestAsk;
    private long BestBid;
    private long LastFixedPrice;

    /** Creates a new Builder */
    private Builder() {
      super(fr.finaxys.tutorials.utils.avro.models.Tick.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(fr.finaxys.tutorials.utils.avro.models.Tick.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Trace)) {
        this.Trace = data().deepCopy(fields()[0].schema(), other.Trace);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.NumTick)) {
        this.NumTick = data().deepCopy(fields()[1].schema(), other.NumTick);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.NumDay)) {
        this.NumDay = data().deepCopy(fields()[2].schema(), other.NumDay);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ObName)) {
        this.ObName = data().deepCopy(fields()[3].schema(), other.ObName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Timestamp)) {
        this.Timestamp = data().deepCopy(fields()[4].schema(), other.Timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.BestAsk)) {
        this.BestAsk = data().deepCopy(fields()[5].schema(), other.BestAsk);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.BestBid)) {
        this.BestBid = data().deepCopy(fields()[6].schema(), other.BestBid);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.LastFixedPrice)) {
        this.LastFixedPrice = data().deepCopy(fields()[7].schema(), other.LastFixedPrice);
        fieldSetFlags()[7] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Tick instance */
    private Builder(fr.finaxys.tutorials.utils.avro.models.Tick other) {
            super(fr.finaxys.tutorials.utils.avro.models.Tick.SCHEMA$);
      if (isValidValue(fields()[0], other.Trace)) {
        this.Trace = data().deepCopy(fields()[0].schema(), other.Trace);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.NumTick)) {
        this.NumTick = data().deepCopy(fields()[1].schema(), other.NumTick);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.NumDay)) {
        this.NumDay = data().deepCopy(fields()[2].schema(), other.NumDay);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ObName)) {
        this.ObName = data().deepCopy(fields()[3].schema(), other.ObName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Timestamp)) {
        this.Timestamp = data().deepCopy(fields()[4].schema(), other.Timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.BestAsk)) {
        this.BestAsk = data().deepCopy(fields()[5].schema(), other.BestAsk);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.BestBid)) {
        this.BestBid = data().deepCopy(fields()[6].schema(), other.BestBid);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.LastFixedPrice)) {
        this.LastFixedPrice = data().deepCopy(fields()[7].schema(), other.LastFixedPrice);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'Trace' field */
    public java.lang.CharSequence getTrace() {
      return Trace;
    }
    
    /** Sets the value of the 'Trace' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder setTrace(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Trace = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'Trace' field has been set */
    public boolean hasTrace() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'Trace' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder clearTrace() {
      Trace = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'NumTick' field */
    public java.lang.Integer getNumTick() {
      return NumTick;
    }
    
    /** Sets the value of the 'NumTick' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder setNumTick(int value) {
      validate(fields()[1], value);
      this.NumTick = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'NumTick' field has been set */
    public boolean hasNumTick() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'NumTick' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder clearNumTick() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'NumDay' field */
    public java.lang.Integer getNumDay() {
      return NumDay;
    }
    
    /** Sets the value of the 'NumDay' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder setNumDay(int value) {
      validate(fields()[2], value);
      this.NumDay = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'NumDay' field has been set */
    public boolean hasNumDay() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'NumDay' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder clearNumDay() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ObName' field */
    public java.lang.CharSequence getObName() {
      return ObName;
    }
    
    /** Sets the value of the 'ObName' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder setObName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ObName = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ObName' field has been set */
    public boolean hasObName() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ObName' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder clearObName() {
      ObName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'Timestamp' field */
    public java.lang.Long getTimestamp() {
      return Timestamp;
    }
    
    /** Sets the value of the 'Timestamp' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder setTimestamp(long value) {
      validate(fields()[4], value);
      this.Timestamp = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'Timestamp' field has been set */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'Timestamp' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'BestAsk' field */
    public java.lang.Long getBestAsk() {
      return BestAsk;
    }
    
    /** Sets the value of the 'BestAsk' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder setBestAsk(long value) {
      validate(fields()[5], value);
      this.BestAsk = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'BestAsk' field has been set */
    public boolean hasBestAsk() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'BestAsk' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder clearBestAsk() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'BestBid' field */
    public java.lang.Long getBestBid() {
      return BestBid;
    }
    
    /** Sets the value of the 'BestBid' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder setBestBid(long value) {
      validate(fields()[6], value);
      this.BestBid = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'BestBid' field has been set */
    public boolean hasBestBid() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'BestBid' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder clearBestBid() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'LastFixedPrice' field */
    public java.lang.Long getLastFixedPrice() {
      return LastFixedPrice;
    }
    
    /** Sets the value of the 'LastFixedPrice' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder setLastFixedPrice(long value) {
      validate(fields()[7], value);
      this.LastFixedPrice = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'LastFixedPrice' field has been set */
    public boolean hasLastFixedPrice() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'LastFixedPrice' field */
    public fr.finaxys.tutorials.utils.avro.models.Tick.Builder clearLastFixedPrice() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public Tick build() {
      try {
        Tick record = new Tick();
        record.Trace = fieldSetFlags()[0] ? this.Trace : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.NumTick = fieldSetFlags()[1] ? this.NumTick : (java.lang.Integer) defaultValue(fields()[1]);
        record.NumDay = fieldSetFlags()[2] ? this.NumDay : (java.lang.Integer) defaultValue(fields()[2]);
        record.ObName = fieldSetFlags()[3] ? this.ObName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.Timestamp = fieldSetFlags()[4] ? this.Timestamp : (java.lang.Long) defaultValue(fields()[4]);
        record.BestAsk = fieldSetFlags()[5] ? this.BestAsk : (java.lang.Long) defaultValue(fields()[5]);
        record.BestBid = fieldSetFlags()[6] ? this.BestBid : (java.lang.Long) defaultValue(fields()[6]);
        record.LastFixedPrice = fieldSetFlags()[7] ? this.LastFixedPrice : (java.lang.Long) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
